### ISSUE TITLE
Resources to Understand This Codebase?

### ISSUE THREAD

**Issue by aunyks** [gkjohnson/closed-chain-ik-js#90]
Hey Garrett!

This is an awesome project and it's well written. That said, do you know of any resources (maybe textbooks from school?) where I can better understand the IK math behind it? I'm pretty sure I understand how a `Solver` relates to a `Goal`, `Joint`, and `Link`, but my understanding of the IK below it all is pretty weak.

Love all the dope projects you're doing and thanks for the help

**Comment by gkjohnson** [comment]
Hello! Glad to hear you're enjoying the work.

The paper I link in the README by [Samuel Buss in 2009](https://math.ucsd.edu/~sbuss/ResearchWeb/ikmethods/iksurvey.pdf) is a overview of the approach and should provide enough details on how to implement the solver or at least provide enough information to look up math topics you aren't familiar with, yet.

Even with that paper, though, there are still quirks particularly around rotations that the paper might not touch on in too much detail if I recall, and that I still haven't fixed in this repo. Specifically you should prefer rotations that are continuous and don't suffer from something like gimbal lock or redundant representations (ie not Euler angles) so the solver can correctly take small steps toward the one solution without getting stuck. Perhaps at some point I'll make the effort to fix rotations but I've since moved on to new projects.

IK is a fairly deep topic especially for robotics and afaik there are other, more modern solutions out there, as well, which I'd still like to learn more about. Unfortunately it doesn't seem to be a topic that's commonly written about in a very approachable way. Hopefully the above paper with the implementation from this repo can help shed some more light on the topic for you!

**Comment by aunyks** [comment]
Thanks for the help!
